-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 20:52:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbic` ;

-- -----------------------------------------------------
-- Schema dbic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbic` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `dbic` ;

-- -----------------------------------------------------
-- Table `dbic`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbic`.`producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dbic`.`producto` (
  `product_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(255) NULL DEFAULT NULL,
  `codigo` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_vencimiento` DATETIME NULL DEFAULT NULL,
  `precio` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `dbic`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbic`.`reserva` ;
SHOW WARNINGS;

CREATE TABLE IF NOT EXISTS `dbic`.`reserva` (
  `product_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(255) NULL DEFAULT NULL,
  `codigo` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_vencimiento` DATETIME NULL DEFAULT NULL,
  `precio` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
